# Site settings
title: Gergely Máthé
description: Gergely Máthé's personal website
baseurl: "https://gergelymathe.github.io" # the subpath of your site, e.g. /blog
url: "https://gergelymathe.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gergely Máthé
user_description: Have more than 5 years of experience in computational problem solving ranging from implementation of high performance computing simulations to applying various machine learning techniques. Mostly work in a collaborative environment on multidisciplinary topics such as statistical modelling of gravitating many body systems or machine learning adapted space weather monitoring. Due to the scope of research interest, working with cutting edge computational methods and techniques on a daily basis. Currently engaged in the last year of an astrophysics PhD program with a special focus on computational astrophysics.
user_title: Machine learning research scientist | Computational astrophysicist | Final year astrophysics PhD student
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: gergelymathe
github_username:  gergelymathe
email: gergely.mathe07@gmail.com
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
